openapi: "3.0.0"
info:
  title: PDF Generator API
  version: 1.0.0
  description: Document of PDF generator
paths:
  /health-check:
    get:
      responses:
        '200':
          description: NOT OKAY
  /generate-pdf:
    post:
      summary: Generate PDF from input text
      operationId: generatePdf
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userInput:
                  type: string
      responses:
        '200':
          description: PDF generated successfully
          content:
            application/pdf:
              schema:
                type: string
                format: binary

  /scrape:
    get:
      summary: Scrape data from a webpage and save to database
      operationId: scrapeDataAndSave
      parameters:
        - in: query
          name: url
          required: true
          schema:
            type: string
          description: The URL of the webpage to scrape
        - in: query
          name: wordNumHeader
          required: true
          schema:
            type: string
          description: The header name for the word number
        - in: query
          name: wordHeader
          required: true
          schema:
            type: string
          description: The header name for the word
        - in: query
          name: wordMeaningHeader
          required: true
          schema:
            type: string
          description: The header name for the word meaning
      responses:
        '200':
          description: Data scraped and saved successfully

  /word-books:
    get:
      tags:
        - WordBooks
      summary: Retrieve a list of word books
      description: Fetches a list of available word books from the database.
      operationId: getWordBooks
      responses:
        '200':
          description: A list of word books
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "English Basics"
        '500':
          description: Internal Server Error

  /test-options:
    get:
      tags:
        - Section and wordCount
      summary: Retrieve a map of section and word count
      description: Fetches a map of section and word count related to the selected word book from the database.
      operationId: getSectionAndWordCount
      parameters:
        - in: query
          name: wordBook
          required: true
          schema:
            type: string
          description: The word book for which to fetch sections and word count
      responses:
        '200':
          description: A map of sections and word counts
          content:
            application/json:
              schema:
                type: object  # Mapを表現するためにobjectを使用
                additionalProperties: # キーと値の型を定義
                  type: integer  # セクションごとの単語数
                  format: int64  # セクションごとの単語数
                  example: 10
                description: "Map where keys are section names and values are word counts"
        '500':
          description: Internal Server Error

  /create-test:
    post:
      summary: Generate test from input options
      operationId: generateTest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                word_book:
                  type: string
                  description: "The name of the word book"
                sections:
                  type: array
                  items:
                    type: string
                  description: "The list of section names to retrieve words from"
                word_num:
                  type: integer
                  description: "The number of words to retrieve"
      responses:
        '200':
          description: Test generated successfully
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/TestItem'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

components:
  schemas:
    TestItem:
      type: object
      properties:
        wordBook:
          type: string
          description: "The word book"
        word:
          type: string
          description: "The word"
        meaning:
          type: string
          description: "The meaning of the word"
        section:
          type: string
          description: "The section name"
        wordNum:
          type: integer
          format: int32
          description: "The word number"